version: '3.8'

services:
  redis:
    image: redis
    container_name: langgraph-redis
    ports:
      - "6355:6379"
    volumes:
      - radops_data:/data
    command: redis-server --appendonly yes

  weaviate:
    image: semitechnologies/weaviate:1.25.4
    container_name: weaviate
    ports:
      - "8088:8080"
      - "50051:50051"
    environment:
      AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED: 'true'
      PERSISTENCE_DATA_PATH: '/var/lib/weaviate'
      DEFAULT_VECTORIZER_MODULE: 'none'
      ENABLE_MODULES: 'text2vec-openai'
      CLUSTER_HOSTNAME: 'node1'
    volumes:
      - weaviate_data:/var/lib/weaviate

  vault:
    image: hashicorp/vault
    container_name: dev-vault
    cap_add:
      - IPC_LOCK
    ports:
      - "8200:8200"
    environment:
      VAULT_DEV_ROOT_TOKEN_ID: 'my-dev-token'

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "3000:3000"

volumes:
  radops_data:
  weaviate_data: