slack:
  bot_token: vault:integrations#slack_bot_token
  app_token: vault:integrations#slack_app_token

github:
  github_default:
    token: vault:integrations#github_token
    base_url: https://api.github.com/