mcp_servers:
  aws-network-mcp-server:
    transport: "stdio"
    command: "docker"
    args:
      - "run"
      - "--rm"
      - "-i"
      - "-e"
      - "AWS_ACCESS_KEY_ID"
      - "-e"
      - "AWS_SECRET_ACCESS_KEY"
      - "-e"
      - "FASTMCP_LOG_LEVEL" 
      - "--entrypoint"
      - "sh"
      - "awslab/aws-network-mcp-server"
      - "-c"
      - "awslabs.aws-network-mcp-server 2> /dev/null"
    env:
      FASTMCP_LOG_LEVEL: "ERROR"
      AWS_ACCESS_KEY_ID: "vault:tools/aws#ACCESS_KEY_ID"
      AWS_SECRET_ACCESS_KEY: "vault:tools/aws#SECRET_ACCESS_KEY"

  test-mcp-server:
    url: "http://localhost:8000/mcp"
    transport: "streamable_http"

  pagerduty: 
    url: "https://mcp.pagerduty.com/mcp"
    transport: "streamable_http"
    headers: 
      Authorization: "vault:tools/pagerduty#token"

  notion:
    transport: "stdio"
    command: "docker"
    args:
      - "run"
      - "--rm"
      - "-i"
      - "-e"
      - "NOTION_TOKEN"
      - "mcp/notion"
    env:
      NOTION_TOKEN: "vault:tools/notion#token"

# Peering DB
peeringdb:
  api_key: "vault:tools/peeringdb#api_key"

# GitHub Configuration
github:
  server: ""

# Jira Configuration
jira:
  server: "https://mehrdadrad.atlassian.net"

# GeoIP
geoip:
  database_path: ~/Downloads/GeoLite2-City.mmdb

# AWS Configuration
aws:
  region: us-west-2
  access_key_id: vault:tools/aws#ACCESS_KEY_ID
  secret_access_key: vault:tools/aws#SECRET_ACCESS_KEY