local_tools:
  - module: services.tools.network.peeringdb.peeringdb
    tools:
      - function: network__get_asn_peering_info
        enabled: true
      - function: network__get_peering_exchange_info
        enabled: true
  - module: services.tools.network.lg.lg
    tools:
      - function: network__verizon_looking_glass
        enabled: true
      - function: network__verizon_looking_glass_locations
        enabled: true
  - module: services.tools.network.geoip.geoip
    tools:
      - function: network__get_geoip_location
        enabled: true
  - module: services.tools.jira.jira_tools
    tools:
      - function: jira_create_ticket
        enabled: true
      - function: jira_search_issues
        enabled: true
  - module: services.tools.network.checkhost.check_host_net
    tools:
      - function: network__check_host
        enabled: true
      - function: network__get_check_host_nodes
        enabled: true
  - module: services.tools.github.issue
    tools:
      - function: github_list_issues
        enabled: true
      - function: github_create_issue
        enabled: true
  - module: services.tools.github.pull_request
    tools:
      - function: github_create_pull_request
        enabled: true
      - function: github_list_pull_requests
        enabled: true
  - module: services.tools.aws.diagnostics
    tools:
      - function: aws__analyze_reachability
        enabled: true
      - function: aws__query_logs
        enabled: true
      - function: aws__check_recent_changes
        enabled: true
      - function: aws__get_ec2_health
        enabled: true
  - module: services.tools.aws.ec2
    tools:
      - function: aws__list_ec2_instances
        enabled: true
      - function: aws__manage_ec2_instance
        enabled: true
  - module: services.tools.aws.troubleshooting
    tools:
      - function: aws__get_cloudformation_stack_events
        enabled: true
      - function: aws__get_target_group_health
        enabled: true
      - function: aws__simulate_iam_policy
        enabled: true
  - module: services.tools.aws.network
    tools:
      - function: aws__manage_vpc
        enabled: true
      - function: aws__manage_subnet
        enabled: true
      - function: aws__manage_internet_gateway
        enabled: true
      - function: aws__manage_route_table
        enabled: true
      - function: aws__manage_route
        enabled: true
  - module: services.tools.nautobot.ipam
    tools:
      - function: nautobot__get_prefix_details
        enabled: true
      - function: nautobot__get_ip_by_host
        enabled: true
  - module: services.tools.nautobot.dcim
    tools:
      - function: nautobot__get_location_by_name
        enabled: true
      - function: nautobot__get_platform_by_name
        enabled: true
  - module: services.tools.nautobot.devices
    tools:
      - function: nautobot__get_device_details
        enabled: true
      - function: nautobot__get_device_interfaces
        enabled: true
  - module: services.tools.nautobot.circuits
    tools:
      - function: nautobot__get_circuit_by_id
        enabled: true


mcp_servers:
  aws-network-mcp-server:
    transport: "stdio"
    command: "docker"
    args:
      - "run"
      - "--rm"
      - "-i"
      - "-e"
      - "AWS_ACCESS_KEY_ID"
      - "-e"
      - "AWS_SECRET_ACCESS_KEY"
      - "-e"
      - "FASTMCP_LOG_LEVEL" 
      - "--entrypoint"
      - "sh"
      - "awslab/aws-network-mcp-server"
      - "-c"
      - "awslabs.aws-network-mcp-server 2> /dev/null"
    env:
      FASTMCP_LOG_LEVEL: "ERROR"
      AWS_ACCESS_KEY_ID: "vault:tools/aws#ACCESS_KEY_ID"
      AWS_SECRET_ACCESS_KEY: "vault:tools/aws#SECRET_ACCESS_KEY"

  test-mcp-server:
    url: "http://localhost:8000/mcp"
    transport: "streamable_http"

  pagerduty: 
    url: "https://mcp.pagerduty.com/mcp"
    transport: "streamable_http"
    headers: 
      Authorization: "vault:tools/pagerduty#token"

  notion:
    transport: "stdio"
    command: "docker"
    args:
      - "run"
      - "--rm"
      - "-i"
      - "-e"
      - "NOTION_TOKEN"
      - "mcp/notion"
    env:
      NOTION_TOKEN: "vault:tools/notion#token"

# Peering DB
peeringdb:
  api_key: "vault:tools/peeringdb#api_key"

# GitHub Configuration
github:
  server: ""

# Jira Configuration
jira:
  server: "https://mehrdadrad.atlassian.net"

# GeoIP
geoip:
  database_path: ~/Downloads/GeoLite2-City.mmdb

# AWS Configuration
aws:
  region: us-west-2
  access_key_id: vault:tools/aws#ACCESS_KEY_ID
  secret_access_key: vault:tools/aws#SECRET_ACCESS_KEY

nautobot:
  url: https://demo.nautobot.com/
  token: aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
  verify_ssl: false